# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r:
    - oldrel
    - release
    - devel
    - bioc-release
    - bioc-devel

warnings_are_errors: true
#env:
#  global:
#    - _R_CHECK_FORCE_SUGGESTS_=false
#    - MAKEFLAGS="-j 2"

#r_github_packages:
#  - hadley/devtools

#before_script:
#  - psql -c 'create database test;' -U postgres

#after_success:
#- Rscript -e 'covr::codecov()'

#notifications
notifications:
    email:
        on_success: change
        on_failure: change
