# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r:
    - bioc-release
    - bioc-devel
#    - oldrel
#    - release
#    - devel
os:
    - linux
    - osx

warnings_are_errors: true
#env:
#  global:
#    - _R_CHECK_FORCE_SUGGESTS_=false
#    - MAKEFLAGS="-j 2"

#r_github_packages:
#  - hadley/devtools

#before_script:
#  - psql -c 'create database test;' -U postgres

r_packages:
    - covr

after_success:
    - Rscript -e 'library(covr); codecov()'

notifications:
    email:
        on_success: change
        on_failure: change

